server:
  port: 8998

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3310/flowable6_demo?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8&nullCatalogMeansCurrent=true
    username: root
    password: 123456

#    pageHelper 配置
pagehelper:
  helper-dialect: mysql #方言
  pageSizeZero: true # 分页参数是否可以为0
  params: count=countSql
  reasonable: true
  support-methods-arguments: true
mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:com/zukxu/**/*.xml
  type-aliases-package: com.zukxu.**.entity

#  flowable配置
flowable:
  database-schema-update: false #创建数据库的规则
  async-executor-activate: false #关闭异步
  check-process-definitions: true #是否需要自动部署流程定义。默认true
  db-history-used: true # 是否要使用db历史。'
  history-level: audit # 要使用的历史级别。'
  idm:
    enabled: false # 是否启用IDM引擎。'