spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss #日期格式化
    #序列化相关配置
    serialization:
      indent-output: true #格式化输出
      fail-on-empty-beans: true #忽略无法转换的对象
    #反序列化相关配置
    deserialization:
      fail-on-unknown-properties: true #忽略不存在的属性
    default-property-inclusion: non_empty #配置空值序列化
    parser:
      allow-unquoted-control-chars: true #允许特殊符号和转义字符
      allow-single-quotes: true #允许单引号