server:
  port: 29898
spring:
  redis:
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        max-wait: 60
        min-idle: 0
    host: 127.0.0.1
    port: 6379
    password:
    # 连接超时时间（毫秒）
    timeout: 2000
    database: 0
