#邮件
spring:
  mail:
    host: smtp.qq.com #配置 SMTP 服务器地址
    port: 587  # SMTP服务器的端口
    username: 1774731598@qq.com #配置邮箱用户名
    password: akbjycdpnqkqeedi #配置授权码
    default-encoding: UTF-8 #默认的邮件编码
    properties:
      mail:
        smtp:
          auth: true
          socketFactoryClass: javax.net.ssl.SSLSocketFactory #配置SSL加密工厂
        debug: true  #表示开启 DEBUG 模式，这样，邮件发送过程的日志会在控制台打印出来，方便排查错误
#端口
server:
  port: 31001
  servlet:
    context-path: /email

#收件者
she:
  mail: zukxu520@163.com